### ISSUE TITLE
Differtiate Functions OnCreate() and Regular Update()

### ISSUE THREAD

**Issue by satishvmadala** [codeforap/CFADeviceManager-Android#1]
When Device is registering for the first time, Standard - Not Changing metrics like Device Model, Name, IMEI, Time of Registration, Owner Information (If any) etc shall be sent to the server as Device_Registration details.

After that, for every 30 Minutes, regular Update of location, time, battery status, data usage etc will be sent to the server.

**Comment by shreyaj** [comment]
Fixed the issue by creating separate tasks. One that runs on creation of service (only once) to send all data to the server. Another one that sends only required data like the location, online status and battery status every 20 minutes.
