### ISSUE TITLE
Change ClientId as a dynamic Variable in the CFAService.Java

### ISSUE THREAD

**Issue by satishvmadala** [codeforap/CFADeviceManager-Android#2]
For every client (MQTT Service on device), there shall be unique-id to establish connection with the Mosquitto Server, hence change the  client id '123' at:
  `new MqttClient(Server, "123", new MemoryPersistence());`
to a dynamic variable which remains unique always when establishing connection to mosquitto.
# If this is not done, two devices cannot speak to the server simultaneously!!

Few Suggestions to arrive logic for dynamic variable:
- Concatanate IMEI + timestamp of connection time + random 4 digit code to arrive 12/16 digit variable.

**Comment by shreyaj** [comment]
Added dynamic client ID based on the IMEI and time.
